### ISSUE TITLE
unconditional_sample.py does not work

### ISSUE THREAD

**Issue by bastiansg** [Elvenson/piano_transformer#5]
Hi!
First of all thank you very much for this project, I have been looking for a long time how to implement this model in a simple way.
I have been trying to run the unconditional_sample.py script inside a Docker container, but I get the following error:

**ValueError: Tensor("body/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/dot_product_attention/attention:0", shape=(), dtype=string, device=/device:GPU:0) must be from the same graph as Tensor("transformer_hparams:0", shape=(), dtype=string).**

I also tried outside the container and i get the same error, this is the complete output:

python unconditional_sample.py -model_path=../data/checkpoints/unconditional_model_16.ckpt -output=/tmp/unconditional.mid -decode_length=1024
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow_gan/python/estimator/tpu_gan_estimator.py:42: The name tf.estimator.tpu.TPUEstimator is deprecated. Ple
ase use tf.compat.v1.estimator.tpu.TPUEstimator instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow_gan/python/estimator/tpu_gan_estimator.py:42: The name tf.estimator.tpu.TPUEstimator is deprecated. Ple
ase use tf.compat.v1.estimator.tpu.TPUEstimator instead.

INFO:tensorflow:Loading model
I0720 03:30:24.636814 140027959473984 unconditional_sample.py:125] Loading model
INFO:tensorflow:Configuring DataParallelism to replicate the model.
I0720 03:30:24.637264 140027959473984 trainer_lib.py:271] Configuring DataParallelism to replicate the model.
INFO:tensorflow:schedule=continuous_train_and_eval
I0720 03:30:24.637380 140027959473984 devices.py:76] schedule=continuous_train_and_eval
INFO:tensorflow:worker_gpu=1
I0720 03:30:24.637479 140027959473984 devices.py:77] worker_gpu=1
INFO:tensorflow:sync=False
I0720 03:30:24.637579 140027959473984 devices.py:78] sync=False
WARNING:tensorflow:Schedule=continuous_train_and_eval. Assuming that training is running on a single machine.
W0720 03:30:24.637644 140027959473984 devices.py:141] Schedule=continuous_train_and_eval. Assuming that training is running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0']
I0720 03:30:24.637947 140027959473984 devices.py:170] datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
I0720 03:30:24.638157 140027959473984 devices.py:171] caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0']
I0720 03:30:24.638301 140027959473984 devices.py:172] ps_devices: ['gpu:0']
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpdw315a7d
W0720 03:30:24.638821 140027959473984 estimator.py:1846] Using temporary folder as model directory: /tmp/tmpdw315a7d
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpdw315a7d', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': 
None, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
    global_jit_level: OFF
  }
}
isolate_session_state: true
, '_keep_checkpoint_max': 20, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_dis
tribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, 'use_tpu': False, 't2t_device_info': {'num_async_replicas': 1}, 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7f5a1843c410>}
I0720 03:30:24.639187 140027959473984 estimator.py:191] Using config: {'_model_dir': '/tmp/tmpdw315a7d', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
    global_jit_level: OFF
  }
}
isolate_session_state: true
, '_keep_checkpoint_max': 20, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, 'use_tpu': False, 't2t_device_info': {'num_async_replicas': 1}, 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7f5a1843c410>}
WARNING:tensorflow:Estimator's model_fn (<function T2TModel.make_estimator_model_fn.<locals>.wrapping_model_fn at 0x7f5a20462950>) includes params argument, but params are not passed to Estimator.
W0720 03:30:24.639431 140027959473984 model_fn.py:617] Estimator's model_fn (<function T2TModel.make_estimator_model_fn.<locals>.wrapping_model_fn at 0x7f5a20462950>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Generating sample.
I0720 03:30:24.639894 140027959473984 unconditional_sample.py:139] Generating sample.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py:1666: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0720 03:30:24.643594 140027959473984 deprecation.py:506] From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py:1666: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensor2tensor/utils/decoding.py:620: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
W0720 03:30:24.643990 140027959473984 deprecation.py:323] From /usr/local/lib/python3.7/dist-packages/tensor2tensor/utils/decoding.py:620: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
WARNING:tensorflow:Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
W0720 03:30:24.645012 140027959473984 estimator.py:1021] Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
INFO:tensorflow:Calling model_fn.
I0720 03:30:24.645307 140027959473984 estimator.py:1169] Calling model_fn.
INFO:tensorflow:Setting T2TModel mode to 'infer'
I0720 03:30:24.654692 140027959473984 t2t_model.py:2267] Setting T2TModel mode to 'infer'
INFO:tensorflow:Setting hparams.dropout to 0.0
I0720 03:30:24.655086 140027959473984 t2t_model.py:2267] Setting hparams.dropout to 0.0
INFO:tensorflow:Setting hparams.label_smoothing to 0.0
I0720 03:30:24.655172 140027959473984 t2t_model.py:2267] Setting hparams.label_smoothing to 0.0
INFO:tensorflow:Setting hparams.layer_prepostprocess_dropout to 0.0
I0720 03:30:24.655304 140027959473984 t2t_model.py:2267] Setting hparams.layer_prepostprocess_dropout to 0.0
INFO:tensorflow:Setting hparams.symbol_dropout to 0.0
I0720 03:30:24.655395 140027959473984 t2t_model.py:2267] Setting hparams.symbol_dropout to 0.0
INFO:tensorflow:Setting hparams.attention_dropout to 0.0
I0720 03:30:24.655459 140027959473984 t2t_model.py:2267] Setting hparams.attention_dropout to 0.0
INFO:tensorflow:Setting hparams.relu_dropout to 0.0
I0720 03:30:24.655512 140027959473984 t2t_model.py:2267] Setting hparams.relu_dropout to 0.0
INFO:tensorflow:Greedy Decoding
I0720 03:30:24.697691 140027959473984 t2t_model.py:2267] Greedy Decoding
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensor2tensor/models/transformer.py:755: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0720 03:30:24.697983 140027959473984 deprecation.py:323] From /usr/local/lib/python3.7/dist-packages/tensor2tensor/models/transformer.py:755: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensor2tensor/layers/common_attention.py:443: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0720 03:30:24.703426 140027959473984 deprecation.py:323] From /usr/local/lib/python3.7/dist-packages/tensor2tensor/layers/common_attention.py:443: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
2020-07-20 03:30:24.986300: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-20 03:30:25.007442: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-20 03:30:25.007724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 with Max-Q Design computeCapability: 6.1
coreClock: 1.48GHz coreCount: 10 deviceMemorySize: 5.94GiB deviceMemoryBandwidth: 178.99GiB/s
2020-07-20 03:30:25.007897: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-20 03:30:25.009001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-20 03:30:25.010080: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-20 03:30:25.010308: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-20 03:30:25.011546: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-20 03:30:25.012366: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-20 03:30:25.015320: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-20 03:30:25.015449: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-20 03:30:25.016055: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-20 03:30:25.016305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensor2tensor/models/transformer.py:159: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0720 03:30:25.026270 140027959473984 deprecation.py:506] From /usr/local/lib/python3.7/dist-packages/tensor2tensor/models/transformer.py:159: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensor2tensor/layers/common_layers.py:2883: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.random.categorical` instead.
W0720 03:30:27.968917 140027959473984 deprecation.py:323] From /usr/local/lib/python3.7/dist-packages/tensor2tensor/layers/common_layers.py:2883: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.random.categorical` instead.
INFO:tensorflow:Done calling model_fn.
I0720 03:30:28.157105 140027959473984 estimator.py:1171] Done calling model_fn.
Traceback (most recent call last):
  File "unconditional_sample.py", line 169, in <module>
    console_entry_point()
  File "unconditional_sample.py", line 165, in console_entry_point
    utils.tf.compat.v1.app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "unconditional_sample.py", line 160, in main
    run()
  File "unconditional_sample.py", line 140, in run
    sample_ids = next(unconditional_samples)['outputs']
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 629, in predict
    hooks=all_hooks) as mon_sess:
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1038, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 749, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1231, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1236, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 902, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 660, in create_session
    self._scaffold.finalize()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 232, in finalize
    summary.merge_all)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 297, in get_or_default
    op = default_constructor()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/summary/summary.py", line 406, in merge_all
    return merge(summary_ops, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/summary/summary.py", line 370, in merge
    with _ops.name_scope(name, 'Merge', inputs):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 6284, in __enter__
    g_from_inputs = _get_graph_from_inputs(self._values)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 5921, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 5856, in _assert_same_graph
    (item, original_item))
ValueError: Tensor("body/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/dot_product_attention/attention:0", shape=(), dtype=string, device=/device:GPU:0) must be from the same graph as Tensor("transformer_hparams:0", shape=(), dtype=string).

do you know what the problem may be?

Im using:

python: 3.7.5
magenta: 2.1.0
tensorflow: 2.2.0

**Comment by Elvenson** [comment]
Hi there,
Can you try to pip install the following version for both `magenta` and `tensorflow` and test it again:
- `pip install magenta==1.3.1`
- `pip install tensorflow==1.15.2`
Hope this help!

**Comment by bastiansg** [comment]
Yes!

The problem was the version of tensorflow, with version 1.15.2 and the last version of magenta (2.1.0) it works perfectly!

thank you!
