### ISSUE TITLE
Pre-training model download

### ISSUE THREAD

**Issue by ExitPath** [Elvenson/piano_transformer#8]
Hello, excuse me, I am very interested in this job, but I have two problems when running the code. 1. The download link of the pre-trained model cannot be found. Can you provide it? Specifically including unconditional_model_16.ckpt and melody_conditioned_model_16.ckpt; 2. How to train this music generation model? Thank you！

**Comment by Elvenson** [comment]
Hi there, thanks for pointing out the issue, I just update the README.md on how to download model. Specifically, you can try this command:
```
gsutil -q -m cp -r gs://magentadata/models/music_transformer/checkpoints/* <destination folder>
```
As for how to train this model, currently Google does not open source this as far as I know, but for more information on how they do it you can take a look at their blog: https://magenta.tensorflow.org/piano-transformer. Hope this help!
